### ISSUE TITLE
Timeline moves when swiping away images

### ISSUE THREAD

**Issue by wolfteeth** [DagAgren/toot#135] opened 2018-08-22 00:23 UTC
When viewing an image in a toot, when I swipe the image away, I often find the timeline has moved. Not sure if it's the swipe gesture that causes it or something else happening in the background. This has caused me to unintentionally favorite the wrong toots.

**Comment by DagAgren** [comment] 2018-08-22 07:49
This is a mystery issue causing some other problems too, possibly related to the scroll-to-top bug too? No clue yet what causes it.

**Comment by DagAgren** [comment] 2018-08-31 20:52
Duplicate of https://github.com/DagAgren/toot/issues/118

**Closed by DagAgren** 2018-08-31 20:52 UTC
Labels: bug, tootlines
