### ISSUE TITLE
CW header color glitch

### ISSUE THREAD

**Issue by claus** [DagAgren/toot#460] opened 2020-12-12 22:29 UTC
On my wife's 1st gen iPhone SE (iOS 14.2) the CW banner shows a white/yellow background pattern instead of the usual dark grey/yellow pattern. This happens in all timelines, but does not happen when viewing the toot thread. See screenshots:

![WhatsApp Image 2020-12-12 at 19 22 53](https://user-images.githubusercontent.com/2277/101996327-48e7e600-3cb0-11eb-9d8d-69e546440775.jpeg)

![WhatsApp Image 2020-12-12 at 19 23 45](https://user-images.githubusercontent.com/2277/101996330-4eddc700-3cb0-11eb-99b7-1a1210e65818.jpeg)

**Comment by edebill** [comment] 2020-12-29 12:56
I get the same problem if my iPhone is set to dark mode, regardless of which toot theme I choose. All is well if I switch my iOS theme to light mode. In mine the hidden text behind the CW also shows as extra light compared to how it looks in the thread view.

**Comment by claus** [comment] 2020-12-30 01:03
FYI my wife's SE does _not_ run in dark mode

**Comment by DagAgren** [comment] 2021-02-20 21:29
Are these on the latest app version? There used to be some bugs related to this but they should be fixed now and I can't reproduce this.

**Comment by DagAgren** [comment] 2021-02-20 21:41
Just as I posted that, I managed to reproduce it. Sigh. Let's see if I can fix it.

**Comment by DagAgren** [comment] 2021-02-20 22:57
Think I got it working now. Apparently it only happens to any content warnings that are visible on screen when the app starts up, which is why I missed it before.

**Closed by DagAgren** 2021-02-20 22:57 UTC
Labels: bug
