### ISSUE TITLE
Content warnings on replies aren’t counted by the character counter

### ISSUE THREAD

**Issue by tychoquad** [DagAgren/toot#294] opened 2019-03-05 21:09 UTC
If you reply to a thread that has a content warning you want to keep, and post near the character limit, it will fail with the toot too long error, despite the character counter saying <500. I quickly found out that it was because the character counter wasn’t applying the characters used by the content warning

**Comment by DagAgren** [comment] 2019-03-07 20:42
I can't reproduce this. The content warning is included in the count for both normal posts and replies for me?

**Comment by tychoquad** [comment] 2019-03-07 20:47
![img_0012](https://user-images.githubusercontent.com/16813583/53987821-2ab59380-4176-11e9-8e89-124f295361c4.jpeg)
Screenshot shows content warning with the text counter at 0/500

Maybe it only happens when you add more to your own toot?

**Comment by fluffy-critter** [comment] 2019-03-09 06:52
I’m reproducing this consistently when I self-reply on a CWed toot. 
![338678A0-45EA-412F-828E-B8FE4CA4091C](https://user-images.githubusercontent.com/347162/54067428-cc7bc580-41f4-11e9-82ae-db2598f96845.png)
![BBCA86D7-753D-4FA4-9696-4462661C2FE2](https://user-images.githubusercontent.com/347162/54067429-cc7bc580-41f4-11e9-8718-7f86ad69dead.png)
![CFA45777-C5C8-496B-BB67-EC6DBD9E0133](https://user-images.githubusercontent.com/347162/54067430-cc7bc580-41f4-11e9-8775-bfab2a5e4476.png)

**Comment by fluffy-critter** [comment] 2019-03-11 19:55
Specifically it only seems to happen when replying to yourself, rather than replying to someone else's toot.

**Comment by tychoquad** [comment] 2019-03-11 20:04
I’ve managed to reproduce it with someone else, see my second post in this thread. I updated it with an example of the person’s @ username counted in the character count, but not the content warning.

**Comment by fluffy-critter** [comment] 2019-03-11 20:06
Ah, yeah, now that's happening for me too. It seems inconsistent though.

**Comment by tychoquad** [comment] 2019-03-11 20:15
Heh, I can’t seem to find a way to NOT reproduce it, I’ve tried hitting the reply button from the timeline, from inside a thread, the ... button and reply from there, as well as the add another button in those places. I first noticed this when tapping on the add another toot text field when crafting an extremely long toot

**Comment by tychoquad** [comment] 2019-03-25 01:15
Short vid of what happens when I reply to a content warning

![IMG_0016](https://user-images.githubusercontent.com/16813583/54889222-9a0de000-4ef7-11e9-9d36-4c9052670c0e.gif)

**Comment by DagAgren** [comment] 2019-04-10 18:36
Think I've got it fixed now.

**Closed by DagAgren** 2019-04-10 18:36 UTC
Labels: can't reproduce
