### ISSUE TITLE
Boosted profile image ends up in wrong place

### ISSUE THREAD

**Issue by bezthomas** [DagAgren/toot#181] opened 2018-09-17 17:03 UTC
Tapping a boosted post shows the post in a new view, including an animation that moves the boosted account's icon to the correct place in the new view. Tapping Home reverses that animation, but restores it to whatever toot is in the middle of the screen, which is not necessarily the original boosted toot.

**Comment by DagAgren** [comment] 2018-09-18 12:17
I think this is a duplicate of an already fixed bug, so I'll close for now. Post more if it is still there in the next version.

**Closed by DagAgren** 2018-09-18 12:17 UTC
