### ISSUE TITLE
Loading more toots direction not working correctly on iOS 13

### ISSUE THREAD

**Issue by tonilampela** [DagAgren/toot#344] opened 2019-08-17 05:23 UTC
Loading more toots to above the current scroll position has not worked on any of the iOS 13 public betas (on beta 6 now). Possibly something to check before GM release?

**Comment by DagAgren** [comment] 2019-08-17 11:50
Duplicate of https://github.com/DagAgren/toot/issues/337

**Closed by DagAgren** 2019-08-17 11:50 UTC
