### ISSUE TITLE
DM bubble modal on iPad seems to break app

### ISSUE THREAD

**Issue by cpsdqs** [DagAgren/toot#474] opened 2021-02-14 08:16 UTC
Tapping on a DM bubble on iPad opens a modal view with the direct message, and then does one of the following:

- causes the screen to become entirely non-responsive to touch input, and does not remove the bubble
- dismisses itself with a genie animation after unrelated touch input (e.g. scrolling), before causing the screen to become non-responsive (still slightly dimmed)
- disappears without any animation (crash?) after unrelated touch input (e.g. scrolling), before causing the screen to become non-responsive (still slightly dimmed)

Can’t test on another iPad atm, but happens on v1.15(128) / iOS 14.4 / iPad 11”

**Comment by VirtualWolf** [comment] 2021-02-14 21:39
FWIW I've seen the exact same issue myself, with exactly the same hardware + software configuration, I just forgot to actually raise an issue about it!

**Comment by DagAgren** [comment] 2021-02-17 00:01
Hmm, I can't reproduce this at all. What could it be that triggers it... Any specific theme?

**Comment by cpsdqs** [comment] 2021-02-17 00:07
Strange; it happens every single time for me. More details:

- iOS theme with auto dark mode (bug occurs in both daytime and nighttime)
- portrait orientation
- logged in with multiple accounts
- enabled timeline tweaks: double tap to boost, filter servers
- app was open on the home tab when the notification was received

**Comment by DagAgren** [comment] 2021-02-17 23:27
Tried some more with basically the exact same conditions on a real device, and it worked fine. What IS going on here...

**Comment by DagAgren** [comment] 2021-02-27 20:43
Ok, I took another stab at this, and thanks to @VirtualWolf's video capture of the bug, I didn't quite manage to reproduce this, but by inserting artificial failures in the code I managed to reproduce the exact same weirdly broken animation, so I am guessing I found the part of the code that fails.

I added a workaround for that case which I did not think could happen, and it seems to work, so HOPEFULLY this is now fixed. Let me know if it turns out it wasn't.

**Closed by DagAgren** 2021-02-27 20:43 UTC
