### ISSUE TITLE
Crash In Media Library

### ISSUE THREAD

**Issue by JonathanGerlach** [DagAgren/toot#198] opened 2018-10-10 16:05 UTC
When you toot and open select from media library, then switch to camera app, take picture, switch back to toot media library, the app crashes instead of reloading the media library.

**Comment by DagAgren** [comment] 2018-10-11 08:08
Are you on the latest version?

**Comment by JonathanGerlach** [comment] 2018-10-11 14:49
Yeah, this was with build 39.

**Comment by DagAgren** [comment] 2018-10-12 08:33
Hmm. That bug should have been fixed in that release...

**Comment by DagAgren** [comment] 2018-10-13 21:56
I can see it in the crash logs, though.

Oh well, can't reproduce this at all but I simplified the reload code and I hope the bug magically went away.

**Closed by DagAgren** 2018-10-13 21:56 UTC
