### ISSUE TITLE
Cannot exit Relax mode

### ISSUE THREAD

**Issue by lamnatos** [DagAgren/toot#273] opened 2019-01-21 13:22 UTC
**Steps to reproduce:**
1. Tap on top right 3dots
1. Select the Relax button
1. Once sufficiently relaxed, tap on top left X

**Expected behavior:**
1. User exits Relax mode
1. User relaxation remains

**Observed behavior:**
1. Top left X button looks pressed
1. Relax mode persists
1. Top left X button is pressed again
1. Relax mode persists
1. Questions arise
1. Agitation appears
1. User relaxation evaporates

**Details**
1. Toot! v1.3 (56)
1. iPhone 8
1. iOS 12.1.2

**Comment by DagAgren** [comment] 2019-01-21 16:58
Weird, it works fine here!

**Comment by lamnatos** [comment] 2019-01-21 17:12
Even weirder, now it works for me too, as long as I press the X for a few seconds. Simply tapping it fails, holding it for a couple of seconds works.

**Comment by MarkusPalcer** [comment] 2019-01-24 05:14
I have experienced the same problem yesterday on my iPhone 7+ iOs 12.1.2 and Toot! 1.3 (53).

**Comment by chucker** [comment] 2019-02-22 22:48
Just tried on my iPhone 8 / iOS 12.2b2 / Toot! 1.4.2.

The first time I tap the X, it turns from white to grey. I have to tap and hold for it to go away. It's not clear if this is by design; if it is, I sure couldn't figure that part out (until I read the comment by @lamnatos above).

**Comment by narFnarF** [comment] 2019-03-31 15:23
I just tried reproducing the issue ~20 times. I think @chucker and @lamnatos are correct in saying that long-pressing the X button make it work, but I was also successful at closing the relax mode with short-presses too. I think the button has a very tiny hit-box and require tapping precisely on it. 

Tested on iPhone 5s, iOS12.

**Comment by SuperTachyon** [comment] 2019-05-13 02:28
I have the same issue in iPad Pro 10.5. Totally reproducible and re-install doesn’t work either.

**Comment by lucascantor** [comment] 2019-05-18 19:03
I always have to hold the top-left `X` button to exit.
Tapping it without holding only makes it change in appearance (indicating the tap is recognized).

Tested:
- 2019-may-18
- iPhone SE
- iOS 12.3
- Toot! 1.7.3

**Comment by DagAgren** [comment] 2019-06-09 19:38
May have figured out a way to fix it, even if I can't reproduce it. Let me know if this still happens after the next release.

**Closed by DagAgren** 2019-06-09 19:38 UTC
Labels: can't reproduce
