### ISSUE TITLE
When app loads, relative times are stale

### ISSUE THREAD

**Issue by JonathanGerlach** [DagAgren/toot#285] opened 2019-01-30 17:17 UTC
When I load the app to view existing data, the relative dates should be recalculated, so they no longer say “1m”, and instead say the correct relative time.

**Comment by DagAgren** [comment] 2019-01-31 09:40
Duplicate of https://github.com/DagAgren/toot/issues/186 I think.

**Closed by DagAgren** 2019-01-31 09:40 UTC
