### ISSUE TITLE
Differentiate between photos and videos 

### ISSUE THREAD

**Issue by DysphoricUnicorn** [DagAgren/toot#346] opened 2019-08-17 17:51 UTC
It’s quite common for me to see an interesting post with something that looks like an image which I don’t quite understand and click on it to read the image description and end up inside the in-app browser displaying a video.

That’s a bit of an annoyance and causes me to waste some of my data as well as sometimes glitching out and showing an empty „safari is playing audio“ notification that I can’t get rid off without playing other audio.

I know it’s a pretty minor issue but having a semi-transparent play button (or something similar) on videos would make my experience with your app a lot better :)

**Comment by DagAgren** [comment] 2019-08-17 21:00
Duplicate of https://github.com/DagAgren/toot/issues/342

**Closed by DagAgren** 2019-08-17 21:00 UTC
