### ISSUE TITLE
User Profile needs loading indicator

### ISSUE THREAD

**Issue by JonathanGerlach** [DagAgren/toot#283] opened 2019-01-30 17:00 UTC
It takes a nondeterministic amount of time to load a profile of a user on another server.  A loading indicator is needed to show that your tap was accepted.

**Comment by DagAgren** [comment] 2019-01-31 09:41
Duplicate of https://github.com/DagAgren/toot/issues/34

**Closed by DagAgren** 2019-01-31 09:41 UTC
