### ISSUE TITLE
Improve instance switcher?

### ISSUE THREAD

**Issue by MsVetraNyx** [DagAgren/toot#263] opened 2019-01-08 05:07 UTC
Hi,

I really like the idea of the actual switcher, it's fun and all, don't get me wrong with that.

But being left handed, and the "barrel" mechanism being located on the right side of the screen, I'm really struggling with it, and end up regularly minimizing the app instead of switching to another timeline.

Could it be possible to allow the user to relocate the "barrel" mecanism on the left hand side of the screen?

**Comment by DagAgren** [comment] 2019-01-08 16:09
Duplicate of 
https://github.com/DagAgren/toot/issues/108.

**Closed by DagAgren** 2019-01-08 16:09 UTC
