### ISSUE TITLE
Update Home feed in background

### ISSUE THREAD

**Issue by iero** [DagAgren/toot#365] opened 2019-11-21 17:56 UTC
The update behaviour is great. 
Toot! keep the position of last read article, even if I refresh the feed.

Is it possible to auto-refresh the feed and write the number of "new" toots to read ?
This is the default behaviour of Tweetbot and it's very convenient.

If we could have the number of new toot as a notification (bubble on the app icon) it will be perfect

**Comment by DagAgren** [comment] 2019-11-21 18:39
Showing the number of unread tweets sounds easy, but it is actually very tricky, since toots are loaded in small batches, and we do not necessarily know how many there are. Otherwise duplicate of https://github.com/DagAgren/toot/issues/13.

**Closed by DagAgren** 2019-11-21 18:39 UTC
