### ISSUE TITLE
Include Photo from Library that is not in Moments

### ISSUE THREAD

**Issue by Kater--S** [DagAgren/toot#255] opened 2018-12-20 11:06 UTC
When trying to include a photo that was previously saved to the library from another app, I can only access the "Moments" section of the photo library which does not include that image. Cannot switch to a different section of the photo library.

**Comment by DagAgren** [comment] 2018-12-20 18:33
Duplicate of 
https://github.com/DagAgren/toot/issues/47

**Closed by DagAgren** 2018-12-20 18:33 UTC
