### ISSUE TITLE
No “reduce motion” support

### ISSUE THREAD

**Issue by maeveynot** [DagAgren/toot#438] opened 2020-07-28 23:18 UTC
iOS has a global accessibility setting:

![79B444A9-25A4-4DEF-B682-F500BC2F1284](https://user-images.githubusercontent.com/37351465/88735223-4c664080-d106-11ea-8453-a1d2adbb8212.jpeg)

It would be really nice if Toot could follow this and not animate every transition. There’s a *lot* of custom animation from the moment you start finding your server to log into, and while it really seems like Toot could otherwise be a great client, this gives me motion sickness and I don’t think I will be able to use it. It looks like you worked hard on these and they’re probably great for people who can handle that sort of thing! But I feel like I’d get a headache pretty soon.

Maybe there’s a setting I can’t find, but there shouldn’t be a custom setting in the app, it should use the OS accessibility setting.

**Comment by DagAgren** [comment] 2020-09-26 18:38
I guess this is a duplicate of https://github.com/DagAgren/toot/issues/384, and also an anagram of it.

**Closed by DagAgren** 2020-09-26 18:38 UTC
Labels: accessibility
