### ISSUE TITLE
App crashes in Posting screen when opening shared photo

### ISSUE THREAD

**Issue by fihu** [DagAgren/toot#292] opened 2019-03-01 09:55 UTC
When composing a toot with a photo via the sharing extension (#97), the app crashes when the shared photo is opened (e.g. to add an image description).

**Comment by fihu** [comment] 2019-03-01 10:00
Hm. Works with normal camera photos, but crashes with HDR images.
Image in question is HDR and was edited + saved with Darkroom.

**Comment by DagAgren** [comment] 2019-03-01 11:01
Could you post the image?

**Comment by fihu** [comment] 2019-03-01 13:28
![img_8377](https://user-images.githubusercontent.com/14976291/53641111-47117780-3c2e-11e9-8995-fe0e04be2866.jpg)
Here it is.

**Comment by DagAgren** [comment] 2019-03-23 22:35
Looks like this is a very weird iOS bug. HDR rendering is not working correctly in extensions, maybe? Trying to draw the focus lines on top of the HDR image seems to be what is crashing.

I'll try to find a way to work around it but not sure how well it will go.

**Comment by DagAgren** [comment] 2019-03-24 10:23
No, can't seem to figure out a workaround at the moment. Trying to convert the image to non-HDR is ALSO crashing for some reason.

**Comment by tewha** [comment] 2019-09-06 00:17
I run into this every time I use the share sheet with Toot (only), too.

Note: I'm not saying it isn't an Apple bug. Seems like the sort of thing that might be. Just adding my experience. :)

**Comment by DagAgren** [comment] 2019-09-13 22:19
Would be good to know if this still happens on iOS 13.

**Comment by fihu** [comment] 2019-09-14 05:27
@DagAgren yes, it does (iOS 13.1 public beta). Happens with non-HDR images as well.

**Comment by DagAgren** [comment] 2019-09-15 17:49
I can't reproduce it on the simulator with iOS 13 with my latest version with other fixes for iOS 13. If it's crashes on normal images, that is probably a different issue.

So I think I'll close this for now, and let's try the new version once it's out.

**Closed by DagAgren** 2019-09-15 17:49 UTC
Labels: bug
