### ISSUE TITLE
Notifications not working.

### ISSUE THREAD

**Issue by holiestone13** [DagAgren/toot#473] opened 2021-02-11 06:46 UTC
I'm not receiving any notifications. I've tried signing in and out, deleting the app, turning notifications off/on in my phone's settings as well as the app... but nothing's working. Another person I know who also uses the app isn't receiving notifications either.

I'm using an iPhone XR. Software version 14.4.
They're using an iPhone 11 Pro. Software version 14.4.

**Comment by DagAgren** [comment] 2021-02-11 13:46
Looks like there is a problem with the notification relay. Not sure what is going on, will investigate.

**Comment by DagAgren** [comment] 2021-02-11 13:55
Ok, I figured out what the issue is, but since I know nothing about Docker I don't really know how to fix it. I posted for some help here: https://mastodon.social/@WAHa_06x36/105712954167254775

**Comment by DagAgren** [comment] 2021-02-12 11:28
Oh yes, this is fixed now, thanks to @Xjs!

**Closed** 2021-02-12 11:29 UTC
