### ISSUE TITLE
Tapping on user picture on a notification should go to their profile

### ISSUE THREAD

**Issue by fluffy-critter** [DagAgren/toot#264] opened 2019-01-08 21:17 UTC
If I get a boost or a favorite from someone on one of my roots, when I tap on their name or user picture it’s because I want to see their profile, not because I want to see my own toot. Right now seeing the profile of someone requires expanding my own toot and then scrolling through the notifications on that to find the person.

**Comment by DagAgren** [comment] 2019-01-09 14:59
Duplicate of https://github.com/DagAgren/toot/issues/163.

**Closed by DagAgren** 2019-01-09 14:59 UTC
